### ISSUE TITLE
Installation issue on CentOS 6.3 / R 3.3.1

### ISSUE THREAD

**Issue by wcornwell** [ropensci/git2r#260]
Strangely I had no trouble installing `git2r` on this system from R 3.2.2, but when I tried to switch to R 3.3.1.  I get a long list of errors and warnings, of which this is the first:

```
libgit2/src/transports/ssh.c: In function ‘ssh_agent_auth’:
libgit2/src/transports/ssh.c:292:2: error: unknown type name ‘LIBSSH2_AGENT’
  LIBSSH2_AGENT *agent = libssh2_agent_init(session);
  ^
```

And then a whole list of warnings about  implicit declaration of functions

sessionInfo is:

```
R version 3.3.1 (2016-06-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.3 (Final)
```

I'm a bit puzzled why everything would work on R 3.2.2 but not R 3.3.1.  Any idea what's going on?

**Comment by stewid** [comment]
Thanks for reporting the issue.
Apologies for the delay, I have been swamped with work.

I don't know why the installation fails, but maybe it's related to #262, which I'm working on.

**Comment by wcornwell** [comment]
Cool.  Not urgent, since I just rolled everything back to 3.2.2, but just let me know when #262 is fixed and I can test it

**Comment by stewid** [comment]
#262 is fixed

**Comment by wcornwell** [comment]
Alas, it's something else, but I've figured out a work-around.  I'll close it for now, unless/until this come up for someone else.. thanks for the help.
