### ISSUE TITLE
Package broken for libssl1.1.0

### ISSUE THREAD

**Issue by jeroenooms** [ropensci/git2r#262]
Debian has bumped libssl-dev to 1.1.0 and it seems that the git2r configure script does not like this:

```
checking for libssl... yes
checking for library containing EVP_EncryptInit... -lcrypto
checking for library containing SSL_library_init... no
configure: error: in `/tmp/RtmpNW5h5D/R.INSTALL96a40565f4/git2r':
configure: error:
  ---------------------------------------------
   The OpenSSL library that is required to
   build git2r was not found.

   Please install:
     libssl-dev    (package on e.g. Debian and Ubuntu)
     openssl-devel (package on e.g. Fedora, CentOS and RHEL)
     openssl       (Homebrew package on OS X)
   and try again.

   If the OpenSSL library is installed on
   your system but the git2r configuration
   is unable to find it, you can specify
   the include and lib path to OpenSSL with:
   R CMD INSTALL --configure-args='--with-libssl-include=INCLUDE_PATH --with-libssl-lib=LIB_PATH' git2r
```

@cboettig

**Comment by fbreitwieser** [comment]
This can be reproduced with the current shiny docker image:

```
docker pull rocker/shiny
docker run -ti --entrypoint /bin/bash rocker/shiny
root@cc03e155cae5:/# R -e 'install.packages("git2r");'
```

**Comment by stewid** [comment]
Hi @jeroenooms ,

I have updated the configuration, could you please help me and test if git2r builds with libssl1.1.0 now.

Thanks

**Comment by achubaty** [comment]
@stewid trying to build this in a Docker image based on `rocker/r-base`.  I've added the necessary system dependencies, and am trying to get `git2r` installed using the following addition to [the Dockerfile](https://hub.docker.com/r/achubaty/r-spatial-base/~/dockerfile/):

```
## TEMPORARY to get fixed version of git2r package
RUN git clone https://github.com/ropensci/git2r.git \
  && R CMD build git2r \
  && R CMD INSTALL git2r_0.15.0.9000.tar.gz

## install devtools
RUN install2.r devtools

## TEMPORARY check devtools installation
RUN Rscript -e 'library("devtools")'
```

During installation of `git2r` I get the following failure:

```
checking for libssl... yes
checking for library containing EVP_EncryptInit... -lcrypto
checking for library containing SSL_library_init... no
checking for library containing OPENSSL_init_ssl... none required
...
<snip>
...
libgit2/src/openssl_stream.c: In function ‘bio_create’:
libgit2/src/openssl_stream.c:159:3: error: dereferencing pointer to incomplete type ‘BIO {aka struct bio_st}’
  b->init = 1;
   ^~
libgit2/src/openssl_stream.c: At top level:
libgit2/src/openssl_stream.c:217:1: error: variable ‘git_stream_bio_method’ has initializer but incomplete type
 static BIO_METHOD git_stream_bio_method = {
 ^~~~~~
libgit2/src/openssl_stream.c:219:2: warning: excess elements in struct initializer
  "git_stream",
  ^~~~~~~~~~~~
libgit2/src/openssl_stream.c:219:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:220:2: warning: excess elements in struct initializer
  bio_write,
  ^~~~~~~~~
libgit2/src/openssl_stream.c:220:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:221:2: warning: excess elements in struct initializer
  bio_read,
  ^~~~~~~~
libgit2/src/openssl_stream.c:221:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:222:2: warning: excess elements in struct initializer
  bio_puts,
  ^~~~~~~~
libgit2/src/openssl_stream.c:222:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:223:2: warning: excess elements in struct initializer
  bio_gets,
  ^~~~~~~~
libgit2/src/openssl_stream.c:223:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:224:2: warning: excess elements in struct initializer
  bio_ctrl,
  ^~~~~~~~
libgit2/src/openssl_stream.c:224:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:225:2: warning: excess elements in struct initializer
  bio_create,
  ^~~~~~~~~~
libgit2/src/openssl_stream.c:225:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c:226:2: warning: excess elements in struct initializer
  bio_destroy
  ^~~~~~~~~~~
libgit2/src/openssl_stream.c:226:2: note: (near initialization for ‘git_stream_bio_method’)
libgit2/src/openssl_stream.c: In function ‘verify_server_cert’:
libgit2/src/openssl_stream.c:342:4: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
    const char *name = (char *) ASN1_STRING_data(gn->d.ia5);
    ^~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from libgit2/src/global.h:22,
                 from libgit2/src/openssl_stream.c:12:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
libgit2/src/openssl_stream.c:397:4: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
    memcpy(peer_cn, ASN1_STRING_data(str), size);
    ^~~~~~
In file included from /usr/include/openssl/bn.h:31:0,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /usr/include/openssl/x509.h:23,
                 from /usr/include/openssl/ssl.h:50,
                 from libgit2/src/global.h:22,
                 from libgit2/src/openssl_stream.c:12:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^
libgit2/src/openssl_stream.c: At top level:
libgit2/src/openssl_stream.c:217:19: error: storage size of ‘git_stream_bio_method’ isn’t known
 static BIO_METHOD git_stream_bio_method = {
                   ^~~~~~~~~~~~~~~~~~~~~
make: *** [libgit2/src/openssl_stream.o] Error 1
/usr/lib/R/etc/Makeconf:132: recipe for target 'libgit2/src/openssl_stream.o' failed
ERROR: compilation failed for package ‘git2r’
* removing ‘/usr/local/lib/R/site-library/git2r’
The command '/bin/sh -c git clone https://github.com/ropensci/git2r.git   && R CMD build git2r   && R CMD INSTALL git2r_0.15.0.9000.tar.gz' returned a non-zero code: 1
```

**Comment by vincentyeung** [comment]
I still see the same error message as @jeroenooms

**Comment by stewid** [comment]
@achubaty, thanks for the build output. I think I have to update the bundled libgit2 to the latest commit to fix this https://github.com/libgit2/libgit2/commit/7175222ce63ef61749cc00a1f29d11d098bd28a8 It might take me a couple of days

**Comment by stewid** [comment]
@achubaty I have updated the bundled libgit2, could you please try to build git2r in the Docker image again.

**Comment by achubaty** [comment]
@stewid it now builds and installs without error. Thanks!

**Comment by stewid** [comment]
Thanks @achubaty

**Comment by cdiener** [comment]
Hi, don't mean to create pressure but it might be worthwhile to push that change to CRAN as big part of the rocker and bioconductor docker images use testing and that bug causes problem in many docker pipelines. Thanks for the great work!

**Comment by cboettig** [comment]
@cdiener Agreed! I keep checking to see if a new version is on CRAN.

 On the Rocker side, we now have a more version-stable stack that builds on `debian:jessie` instead of `debian:testing`, so it is not effected by this issue (and is overall a bit more robust to this kind of thing where libraries get changed on `testing`, albeit at the cost of older libraries).  Compared to the default rocker stack, this stack has some other features as well, might be of interest:  https://github.com/rocker-org/rocker-versioned .  These images are still pretty new, feedback & suggestions welcome.

**Comment by cdiener** [comment]
@cboettig Thanks, also for the work-around in the normal rocker/rstudio. Have switched my Dockerfiles to that one from the bioconductor ones and everything works.

**Comment by stewid** [comment]
@cdiener @cboettig I'm working on a new release and hopefully I find time this weekend to finish.

**Comment by cdiener** [comment]
@stewid Thanks!
