### ISSUE TITLE
Windows build link failure with RTools < 4.2

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [ropensci/git2r#459]
Introduced with fdc6fd82

## Error messages

> undefined reference to `__imp___acrt_iob_func'

<samp>
   C:/rtools40/mingw64/bin/gcc -shared -s -static-libgcc -o git2r.dll git2r-win.def git2r.o git2r_S3.o git2r_arg.o git2r_blame.o git2r_blob.o git2r_branch.o git2r_checkout.o git2r_clone.o git2r_commit.o git2r_config.o git2r_cred.o git2r_diff.o git2r_error.o git2r_graph.o git2r_index.o git2r_libgit2.o git2r_merge.o git2r_note.o git2r_object.o git2r_odb.o git2r_oid.o git2r_push.o git2r_reference.o git2r_reflog.o git2r_remote.o git2r_repository.o git2r_reset.o git2r_revparse.o git2r_revwalk.o git2r_signature.o git2r_stash.o git2r_status.o git2r_tag.o git2r_transfer.o git2r_tree.o -L../windows/libgit2-1.4.2-fixed/lib/x64 -lgit2 -lssh2 -lz -lssl -lcrypto -lwinhttp -lws2_32 -lcrypt32 -lole32 -lrpcrt4 -LC:/Users/[redacted]/R/R-4.0.5/bin/x64 -lR

   C:/rtools40/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ../windows/libgit2-1.4.2-fixed/lib/x64/libgit2.a(diff_print.c.obj):(.text+0x13b7): undefined reference to `__imp___acrt_iob_func'
</samp>
